version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: gql_neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt Protocol
    environment:
      NEO4J_AUTH: "neo4j/test"  # Default credentials: username/password
