// Neo4j automatically creates and maintains a schema for the graph as you define constraints or add data.
// schema constraint to ensure that the name property for nodes with the label Person is unique
CREATE CONSTRAINT FOR (p:Person) REQUIRE p.name IS UNIQUE;